
runtime: python39
service: shortener


env_variables:
  CONFIG_NAME: dev
  FLASK_ENV: development
  SECRET_KEY: abcd1234
  DATABASE_URI: postgresql://admin1:Adc%4022226666@/shortener-1?host=%2Fcloudsql%2Fyacarthar1st%3Aasia-southeast1%3Ashortener-1
